version: 2

updates:
  # Root package.json dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "build(deps):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 5
    reviewers:
      - "@tomblackmore"
    labels:
      - "dependencies"
      - "automated"

  # API app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "build(api):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 3
    reviewers:
      - "@tomblackmore"
    labels:
      - "dependencies"
      - "api"
      - "automated"

  # Web app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "build(web):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 3
    reviewers:
      - "@tomblackmore"
    labels:
      - "dependencies"
      - "web"
      - "automated"

  # UI package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "build(ui):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 3
    reviewers:
      - "@tomblackmore"
    labels:
      - "dependencies"
      - "ui"
      - "automated"

  # TypeScript config dependencies
  - package-ecosystem: "npm"
    directory: "/packages/typescript-config"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "build(typescript-config):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 2
    reviewers:
      - "@tomblackmore"
    labels:
      - "dependencies"
      - "typescript-config"
      - "automated"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci:"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 2
    reviewers:
      - "@tomblackmore"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated" 