blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/tomblackmore/mono-site/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Contributing Guidelines
    url: https://github.com/tomblackmore/mono-site/blob/main/contributing-docs/CONTRIBUTING.md
    about: Learn how to contribute to this project
  - name: 🔧 Coding Standards
    url: https://github.com/tomblackmore/mono-site/blob/main/contributing-docs/coding-standards.md
    about: Review our coding standards and best practices 