name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "✨ [Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Existing Issues
      description: Please search existing issues before creating a new one
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of the monorepo would this feature affect?
      options:
        - API (NestJS)
        - Web App (React Router v7)
        - UI Components
        - Build System
        - Documentation
        - CI/CD
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem you're trying to solve...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: Describe your solution in detail...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered alternative solutions?
      placeholder: Describe any alternative solutions you've considered...

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - "No - backward compatible"
        - "Yes - would require major version bump"
        - "Maybe - needs discussion"
    validations:
      required: true

  - type: checkboxes
    id: feature-scope
    attributes:
      label: Feature Scope
      description: What would this feature include? (Select all that apply)
      options:
        - label: New API endpoints
        - label: New UI components
        - label: New frontend pages/routes
        - label: Database schema changes
        - label: Build system improvements
        - label: Documentation updates
        - label: Testing utilities
        - label: Developer tooling

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Write a user story for this feature
      placeholder: "As a [user type], I want [functionality] so that [benefit]..."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be implemented for this feature to be considered complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve workflow"
        - "High - Blocking current work"
        - "Critical - Essential for project success"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: Any additional information, links, or examples...

  - type: checkboxes
    id: implementation-willingness
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to submit a pull request for this feature

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution Guidelines
      description: Please confirm you have read our guidelines
      options:
        - label: I have read the [contributing guidelines](../contributing-docs/CONTRIBUTING.md)
          required: true 